# Generated by Django 2.1.3 on 2019-07-07 20:45

from django.db import migrations, models
import django.db.models.deletion
import restaurant_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('price', restaurant_tracker.models.CurrencyField(verbose_name='Price')),
                ('comment', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('service', models.CharField(max_length=300)),
                ('speed', models.IntegerField(choices=[(1, 'Slow'), (2, 'Medium'), (3, 'Fast')], default=1, verbose_name='Speed')),
                ('comment', models.CharField(max_length=300)),
                ('isOpen', models.BooleanField(default=True)),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('restaurants', models.ManyToManyField(to='restaurant_tracker.Restaurant', verbose_name='Restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_tracker.Restaurant'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_tracker.User'),
        ),
    ]
