# Generated by Django 2.1.3 on 2019-07-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0002_auto_20190708_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
