# Generated by Django 2.1.3 on 2019-07-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0003_auto_20190708_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(to='restaurant_tracker.Tag', verbose_name='Tags'),
        ),
    ]
