# Generated by Django 2.1.3 on 2019-07-09 02:14

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0004_auto_20190708_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='restaurant_tracker.Tag', verbose_name='Tags'),
        ),
    ]
