# Generated by Django 2.1.3 on 2019-11-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0006_auto_20191105_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_tracker.User'),
        ),
    ]
