# Generated by Django 2.1.3 on 2019-11-06 22:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0007_auto_20191105_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 6), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=10), django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=4), django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=10), django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Rating'),
        ),
    ]
