# Generated by Django 2.1.3 on 2019-11-06 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0008_auto_20191106_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 22, 5, 37, 700882, tzinfo=utc), verbose_name='Date'),
        ),
    ]
