# Generated by Django 2.1.3 on 2019-11-06 22:07

from django.db import migrations
import restaurant_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0010_auto_20191106_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=restaurant_tracker.models.CurrencyField(default=0, verbose_name='Price'),
        ),
    ]
