# Generated by Django 2.1.3 on 2019-11-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0011_auto_20191106_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
