# Generated by Django 3.2 on 2022-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0012_auto_20191106_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
