# Generated by Django 5.0 on 2024-02-18 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0014_alter_menuitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 18), verbose_name='Date'),
        ),
    ]
