# Generated by Django 5.0 on 2024-04-19 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0015_alter_menuitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.FileField(default=None, upload_to='uploads/restaurants/menus/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 18), verbose_name='Date'),
        ),
    ]
