# Generated by Django 5.0 on 2025-03-08 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_tracker', '0016_restaurant_menu_restaurant_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 8), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.FileField(blank=True, upload_to='uploads/restaurants/menus/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
